// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLDSV.Models;

#nullable disable

namespace QLDSV.Migrations
{
    [DbContext(typeof(QldsvContext))]
    [Migration("20260415135954_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QLDSV.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("QLDSV.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("SubjectGroupId")
                        .HasColumnType("int")
                        .HasColumnName("subject_group_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SubjectGroupId" }, "subject_group_id");

                    b.HasIndex(new[] { "StudentId", "SubjectGroupId" }, "uq_grade")
                        .IsUnique();

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("QLDSV.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("Mssv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mssv");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "class_id");

                    b.HasIndex(new[] { "Mssv" }, "mssv")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("QLDSV.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("credits")
                        .HasDefaultValueSql("'3'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("QLDSV.Models.SubjectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "class_id")
                        .HasDatabaseName("class_id1");

                    b.HasIndex(new[] { "SubjectId" }, "subject_id");

                    b.HasIndex(new[] { "TeacherId" }, "teacher_id");

                    b.ToTable("subject_groups", (string)null);
                });

            modelBuilder.Entity("QLDSV.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .IsUnique()
                        .HasDatabaseName("user_id1");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("QLDSV.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("enum('student','teacher','admin')")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QLDSV.Models.Grade", b =>
                {
                    b.HasOne("QLDSV.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("grades_ibfk_1");

                    b.HasOne("QLDSV.Models.SubjectGroup", "SubjectGroup")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectGroupId")
                        .IsRequired()
                        .HasConstraintName("grades_ibfk_2");

                    b.Navigation("Student");

                    b.Navigation("SubjectGroup");
                });

            modelBuilder.Entity("QLDSV.Models.Student", b =>
                {
                    b.HasOne("QLDSV.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("students_ibfk_2");

                    b.HasOne("QLDSV.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("QLDSV.Models.Student", "UserId")
                        .HasConstraintName("students_ibfk_1");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLDSV.Models.SubjectGroup", b =>
                {
                    b.HasOne("QLDSV.Models.Class", "Class")
                        .WithMany("SubjectGroups")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("subject_groups_ibfk_3");

                    b.HasOne("QLDSV.Models.Subject", "Subject")
                        .WithMany("SubjectGroups")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("subject_groups_ibfk_1");

                    b.HasOne("QLDSV.Models.Teacher", "Teacher")
                        .WithMany("SubjectGroups")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("subject_groups_ibfk_2");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QLDSV.Models.Teacher", b =>
                {
                    b.HasOne("QLDSV.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("QLDSV.Models.Teacher", "UserId")
                        .HasConstraintName("teachers_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLDSV.Models.Class", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("SubjectGroups");
                });

            modelBuilder.Entity("QLDSV.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("QLDSV.Models.Subject", b =>
                {
                    b.Navigation("SubjectGroups");
                });

            modelBuilder.Entity("QLDSV.Models.SubjectGroup", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("QLDSV.Models.Teacher", b =>
                {
                    b.Navigation("SubjectGroups");
                });

            modelBuilder.Entity("QLDSV.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
